const courses = [
  {
    id: "google-ads",
    title: "The Ultimate Google Ads Training Course",
    category: "Marketing",
    price: 100,
    mentor: "Jerome Bell",
    image: "./images/google-ads.svg",
  },
  {
    id: "product-mgmt",
    title: "Product Management Fundamentals",
    category: "Management",
    price: 480,
    mentor: "Marvin McKinney",
    image: "./images/product-management.svg",
  },
  {
    id: "hr-analytics",
    title: "HR Management and Analytics",
    category: "HR & Recruiting",
    price: 200,
    mentor: "Leslie Alexander Li",
    image: "./images/hr-analytics.svg",
  },
  {
    id: "brand-management",
    title: "Brand Management & PR Communications",
    category: "Marketing",
    price: 530,
    mentor: "Kristin Watson",
    image: "./images/brand-management.svg",
  },
  {
    id: "graphic-design",
    title: "Graphic Design Basic",
    category: "Design",
    price: 500,
    mentor: "Guy Hawkins",
    image: "./images/graphic-design.svg",
  },
  {
    id: "biz-dev",
    title: "Business Development Management",
    category: "Management",
    price: 400,
    mentor: "Dianne Russell",
    image: "./images/business-development.svg",
  },
  {
    id: "highload",
    title: "Highload Software Architecture",
    category: "Development",
    price: 600,
    mentor: "Brooklyn Simmons",
    image: "./images/highload-architecture.svg",
  },
  {
    id: "hr-selection",
    title: "Human Resources – Selection and Recruitment",
    category: "HR & Recruiting",
    price: 150,
    mentor: "Kathryn Murphy",
    image: "./images/hr-selection.svg",
  },
  {
    id: "ux-human-centered",
    title: "User Experience. Human-centered Design",
    category: "Design",
    price: 240,
    mentor: "Cody Fisher",
    image: "./images/ux-human-centered.svg",
  },
  {
    id: "social-media-marketing",
    title: "Social Media Marketing Strategy",
    category: "Marketing",
    price: 350,
    mentor: "Sarah Johnson",
    image: "./images/brand-management.svg",
  },
  {
    id: "content-marketing",
    title: "Content Marketing Mastery",
    category: "Marketing",
    price: 280,
    mentor: "Michael Chen",
    image: "./images/google-ads.svg",
  },
  {
    id: "project-management",
    title: "Advanced Project Management",
    category: "Management",
    price: 450,
    mentor: "Emily Rodriguez",
    image: "./images/product-management.svg",
  },
  {
    id: "hr-training",
    title: "HR Training and Development Programs",
    category: "HR & Recruiting",
    price: 320,
    mentor: "David Thompson",
    image: "./images/hr-analytics.svg",
  },
  {
    id: "talent-acquisition",
    title: "Talent Acquisition Strategies",
    category: "HR & Recruiting",
    price: 270,
    mentor: "Lisa Anderson",
    image: "./images/hr-selection.svg",
  },
  {
    id: "employee-engagement",
    title: "Employee Engagement and Retention",
    category: "HR & Recruiting",
    price: 380,
    mentor: "Robert Williams",
    image: "./images/business-development.svg",
  },
  {
    id: "frontend-development",
    title: "Modern Frontend Development",
    category: "Development",
    price: 550,
    mentor: "Jennifer Martinez",
    image: "./images/highload-architecture.svg",
  },
  {
    id: "backend-development",
    title: "Backend Development with Node.js",
    category: "Development",
    price: 620,
    mentor: "Thomas Brown",
    image: "./images/graphic-design.svg",
  },
];

const catalogElements = {
  tabs: document.querySelector("[data-tabs]"),
  grid: document.querySelector("[data-catalog-grid]"),
  searchInput: document.querySelector("[data-search-input]"),
  loadMore: document.querySelector("[data-load-more]"),
  cardTemplate: document.querySelector("#course-card-template").content,
};

const catalogConfig = {
  initialVisible: 9,
};

export { courses, catalogElements, catalogConfig };
